services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_container
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong@Passw0rd"
      MSSQL_PID: "Developer"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./datasets:/datasets
    networks:
      - mssql_net
    working_dir: /datasets

volumes:
  mssql_data:


networks:
  mssql_net:
